# Generated by Django 4.0.3 on 2022-03-26 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_upload", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="file",
            table="file",
        ),
        migrations.CreateModel(
            name="FileInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("size", models.CharField(max_length=10)),
                ("type", models.CharField(max_length=10)),
                ("upload_data", models.DateTimeField()),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="file_upload.file",
                    ),
                ),
            ],
            options={
                "db_table": "file_info",
            },
        ),
    ]
